spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/Hospital
  username: postgres
  password: Vn041019

 jpa:
  hibernate:
    ddl-auto: update
    
properties:
  hibernate:
   jdbc:
    non_contextual_creation : true

servlet:
  multipart: 
   enabled: true
   max-file-size: 128KB
   max-request-size: 128KB
